export { createDatabase, default } from "./connection.ts";
export type { ServerRow } from "./servers.ts";
export {
  getServers,
  getServer,
  getServerByProviderId,
  insertServer,
  updateServerStatus,
  updateServer,
  deleteServer,
  updateServerHostKey,
} from "./servers.ts";
export type { AppRow, DnsRecordRow } from "./apps.ts";
export {
  getApps,
  getApp,
  getAppByName,
  getAppByDomain,
  renameApp,
  insertApp,
  insertAppWithFirstReplica,
  getServersForApp,
  gcServerIfEmpty,
  hasRunningReplicas,
  hasAnyReplicas,
  updateAppStatus,
  updateAppSleepingState,
  clearAppSleepingState,
  updateAppDeployedBy,
  appendDeployLog,
  getDeployLog,
  deleteApp,
  insertDnsRecord,
  getDnsRecords,
  deleteDnsRecord,
  updateAppEnvVars,
  updateAppContainerPort,
  updateAppDomain,
  updateAppVolume,
  updateAppAuthPassword,
  updateAppDeployMode,
  updateAppWebhook,
  updateAppScaling,
  nextReplicaHostPort,
} from "./apps.ts";
export type { ReplicaRow, MetricSampleRow, ScalingEventRow } from "./replicas.ts";
export {
  insertReplica,
  getReplicas,
  getReplica,
  getReplicasByServer,
  updateReplicaStatus,
  markReplicaStopped,
  markReplicaRunning,
  updateReplicaMetrics,
  deleteReplica,
  getAllReplicas,
  touchReplicaHealth,
  incrementUnhealthyTicks,
  resetUnhealthyTicks,
  insertMetricSample,
  getRecentAppMetrics,
  pruneOldMetrics,
  insertScalingEvent,
  getScalingEvents,
} from "./replicas.ts";
export type { DeploymentRow, DeployJobRow, DeployJobEventRow } from "./deployments.ts";
export {
  insertDeployment,
  updateDeploymentStatus,
  appendDeploymentLog,
  updateDeploymentGitCommit,
  getDeployments,
  getDeployment,
  createDeployJob,
  appendDeployJobEvent,
  finishDeployJob,
  getDeployJob,
  getDeployJobEvents,
} from "./deployments.ts";
export type { UserRow, WebAuthnCredential, Permission } from "./users.ts";
export {
  ALL_PERMISSIONS,
  getUserCount,
  getUserByUsername,
  getUserById,
  getUsers,
  insertUser,
  updateUserPassword,
  deleteUser,
  updateUserGitHub,
  clearUserGitHub,
  setTotpSecret,
  enableTotp,
  disableTotp,
  getTotpSecret,
  insertBackupCodes,
  getUnusedBackupCodes,
  markBackupCodeUsed,
  getUnusedBackupCodeCount,
  insertWebAuthnCredential,
  getWebAuthnCredentials,
  getWebAuthnCredentialById,
  updateWebAuthnCounter,
  deleteWebAuthnCredential,
  enableWebAuthn,
  disableWebAuthn,
  getWebAuthnCredentialCount,
  getUserPermissions,
  hasPermission,
  setUserPermissions,
} from "./users.ts";
export { getSettings, saveSetting } from "./settings.ts";
export { getDeploySession, saveDeploySession, deleteDeploySession } from "./deploy-sessions.ts";
export type { PanelRow, PanelDeploymentRow } from "./panel.ts";
export {
  getPanel,
  insertPanel,
  updatePanelStatus,
  updatePanelEnvVars,
  appendPanelDeployLog,
  getPanelDeployLog,
  updatePanelWebhook,
  updatePanelDnsRecord,
  deletePanel,
  insertPanelDeployment,
  getPanelDeployments,
} from "./panel.ts";
export type {
  ServiceRow,
  ServiceInstanceRow,
  ServiceLinkRow,
  ServiceLinkWithAppRow,
  ServiceLinkWithServiceRow,
  ServiceDeployJobRow,
  ServiceDeployJobEventRow,
} from "./services.ts";
export {
  insertService,
  getService,
  getServiceByName,
  getServices,
  updateServiceStatus,
  updateServiceCredentials,
  deleteService,
  insertServiceInstance,
  getServiceInstances,
  getServiceInstance,
  getPrimaryInstance,
  getAllServiceInstances,
  getServiceInstancesByServer,
  updateServiceInstanceStatus,
  updateServiceInstanceMetrics,
  touchServiceInstanceHealth,
  incrementServiceInstanceUnhealthyTicks,
  resetServiceInstanceUnhealthyTicks,
  deleteServiceInstance,
  nextServiceHostPort,
  insertServiceLink,
  deleteServiceLink,
  getServiceLinks,
  getLinkedServices,
  getServicesOnServer,
  createServiceDeployJob,
  appendServiceDeployJobEvent,
  finishServiceDeployJob,
  getServiceDeployJob,
  getServiceDeployJobEvents,
} from "./services.ts";
